apiVersion: v2
name: kube-prometheus-stack
type: application
version: 1.0.0

dependencies:
  - name: kube-prometheus-stack
    version: ">= 61.0.0, < 62.0.0"
    repository: https://prometheus-community.github.io/helm-charts
