apiVersion: v2
name: external-dns
type: application
version: 1.0.0

dependencies:
  - name: external-dns
    version: ">= 1.14.5, < 2.0.0"
    repository: https://kubernetes-sigs.github.io/external-dns/
