apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crd
  namespace: argocd
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ./config/crd/gateway-api/standard
    repoURL: https://github.com/nginxinc/nginx-gateway-fabric
    targetRevision: v1.3.0
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - Replace=true
