apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  destination:
    namespace: httpbin
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ./services/httpbin/overlays/concorda-dev-do-fra1
    repoURL: https://github.com/concordalabs/infra
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    managedNamespaceMetadata:
      labels:
        nginx-gateway.concordalabs.com/public: "true"
    syncOptions:
      - CreateNamespace=true
      - Replace=true
