apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: ./services/traefik
    repoURL: https://github.com/concordalabs/infra
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
        - values-{{ .Values.spec.clusterName }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
