apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app
  labels:
    app: app
    app.kubernetes.io/name: app
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
