apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - hpa.yaml
  - pdb.yaml
  - service.yaml

buildMetadata: [managedByLabel]

configMapGenerator:
  - name: app # If no dummy is added, it has issues on keeping hashes and sufixes https://github.com/kubernetes-sigs/kustomize/issues/710
