# Source: app/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app
  labels:
    app: app
    app.kubernetes.io/name: app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: app
      app.kubernetes.io/name: app
